import numpy as np
from .._logging import logging
from anndata import AnnData
from ._layers import LayerConfig

from .._utils import _get_memberships

def rep_correlation(
        adata: AnnData,
        layer: LayerConfig,
        obs_key: str,
        *,
        use_cached_mask = False
):
    """
    Compute Spearman correlation between groups defined by an obs column.

    For each group in ``adata.obs[obs_key]``, computes the mean expression
    profile across features, then calculates the pairwise Spearman correlation
    matrix between groups.

    Parameters
    ----------
    adata
        Annotated data matrix
    layer
        Layer configuration specifying which data layer to use
    obs_key
        Key in ``adata.obs`` defining group memberships
    use_cached_mask
        Whether to use a previously cached feature mask

    Returns
    -------
    corrs : np.ndarray
        Spearman correlation matrix of shape (n_groups, n_groups)
    labels : list[str]
        Group labels corresponding to rows/columns of the correlation matrix
    """

    X = layer.transform(adata, use_cached_mask=use_cached_mask)
    cats, cat_names, uq_cats = _get_memberships(adata, obs_key)

    masks = []
    labels = []
    for uq in uq_cats:
        masks.append(cats == uq)
        labels.append(cat_names[uq])

    allrow = np.array([
        X[mask].sum(axis=0).A1 / mask.sum()
        for mask in masks
    ]).T
    import scipy.stats as sts
    corrs = sts.spearmanr(allrow, axis=0).statistic
    return corrs, labels



def group_correlation(
        adata: AnnData,
        uns_keys: list[str],
        uns_activity_keys: list[str],
        *,
        use_spearman: bool = False
) -> np.ndarray:
    """
    Generate correlation matrix. Before using this functions, you should summarize data
    over .obs categorical groups.

    Parameters
    ----------
    adata
    uns_keys
        Key of data in .uns generated by :func:`summarize_data`
    uns_activity_keys
        Key of activity data in .uns generated by :func:`summarize_data`

    Returns
    -------
    Correlation matrix
    """

    _pass = np.array([(adata.uns[k].sum(axis=1) != 0) for k in uns_activity_keys])
    _pass = np.prod(_pass, axis=0).astype(np.bool_)

    allrow = np.c_[
        *(
            adata.uns[k][_pass]
            for k in uns_keys
        )
    ]
    logging.info(f"Shape of matrix for correlation calculations is {allrow.shape}")

    import scipy.stats as sts
    corrs = np.zeros((allrow.shape[1], allrow.shape[1]), dtype=np.float32)

    for i in range(corrs.shape[0]):
        for j in range(corrs.shape[1]):
            if use_spearman:
                corrs[i, j] = sts.spearmanr(allrow[:, i], allrow[:, j], axis=0)[0]
            else:
                corrs[i, j] = sts.pearsonr(allrow[:,i], allrow[:,j], axis=0).statistic
    return corrs