import numpy as np
from anndata import AnnData

from .._logging import logging
from .._utils import ArgAssert, _check_obs_uq, _get_membership
from ..advanced._landscape_config import LandscapeScaffold, _verify_numeric
from ..graph._neighbors import _neighbor_graph
from ..graph._graph import Graph

def landscape(
        adata: AnnData,
        scaffold: LandscapeScaffold,
        y_key: str,
        embedding_key: str,
        *,
        obsp_key: str | None = None,
        community_key: str = "leiden",
        y_mean_init: bool = False,
        force_post_y: bool = True,
        # scaffold_scale: float = 1,
        umap_epochs: int = 5,
        umap_spread: float = 1,
        umap_min_dist: float = 0.05,
        return_coarse: bool = False
) -> None:
    """
    Create landscape based on neighborhood clusters, using leaf-clusters for inter-slice alignment. \
    This function uses information from `.obsp['distances']`

    Parameters
    ----------
    adata
    scaffold:
        A :class:`LandscapeScaffold` instance identifying leaf-clusters
    y_key
        Key in .obs to use for y-coordinate of cell on landscape. This is usually (pseudo)time
    embedding_key
        Embedding to use in UMAP transform
    community_key
        Categorical for communities
    y_mean_init
        Whether to use y_key per cell y-coordinate (continuous) or per cluster-mean for initial embedding
    force_post_y
        Whether to replace y-coordinate post-UMAP with y_key or leave new y-coordinate generated by UMAP
    umap_epochs
        How many UMAP epochs to run
    return_coarse
        Whether to return coarse embedding
        
    Returns
    -------
    `adata.obsm['X_landscape']`. 
        Landscape embedding

    `adata.obsm['X_coarse_landscape']` 
        Only if return_coarse is `True`
    """
    graph = _neighbor_graph(adata, obsp_key=obsp_key)
    from tqdm.notebook import tqdm
    with tqdm(total=9) as pbar:
        pbar.n = 0
        pbar.refresh()

        def _upd() -> None:
            pbar.n += 1
            pbar.refresh()

        ArgAssert('distances' in adata.obsp.keys(), "Distances are missing from .obsp")
        ArgAssert(embedding_key in adata.obsm.keys(), "embedding_key is missing from .obsm")

        if umap_epochs > 10:
            logging.warning("The provded number of epochs might be too big. The landscape will become fragmented")

        _check_obs_uq(adata)
        _upd()
        graph._check_graph(adata)
        scaffold._check_obs(adata)

        #new membership
        _membership = _get_membership(adata, community_key)
        vcount = np.unique(_membership).shape[0]
        _verify_numeric(adata, y_key)

        index = np.array(adata.obs.index.tolist())

        _upd()
        ### scaffold prepare
        i = np.argsort(index)
        sorted_x = index[i]
        scaffold_cell_indices = i[np.searchsorted(sorted_x, scaffold.obs_indices)]

        cells_by_cluster = [np.arange(adata.shape[0])[_membership == i] for i in range(_membership.max() + 1)]

        n_scaffold_leaves = len(scaffold.memberships)

        #membersips: leiden 0: [obs indices..], 1: [...], 2: [...] etc
        logging.info(f"Creating layout using {n_scaffold_leaves} leaf clusters")
        xs = np.argsort(scaffold.order) / scaffold.order.max()

        _upd()
        ### do the layout

        # TODO: what is this?
        # weights based on how many barcodes are in the leaf clusters
        id_weights = np.array([
            [np.isin(np.array(cells_by_cluster[j]), scaffold_cell_indices[scaffold.memberships[i]]).sum() for i in range(n_scaffold_leaves)]
            for j in range(vcount)
        ])

        _upd()

        # weights based on how many edges to barcodes in the leaf clusters
        edges = np.array(graph.edges)
        c_edges = [
            [np.concatenate((
                edges[np.isin(edges[:, 0], np.array(cells_by_cluster[j]))][:, 1],
                edges[np.isin(edges[:, 1], np.array(cells_by_cluster[j]))][:, 0]
            ))]
            for j in range(vcount)
        ]

        c_weights = np.array([
            [np.isin(c_edges[j], scaffold_cell_indices[scaffold.memberships[i]]).sum() for i in range(n_scaffold_leaves)]
            for j in range(vcount)
        ])

        _upd()

        _xlayout = np.array([
            np.array([xs[i] * c_weights[j][i] for i in range(n_scaffold_leaves)]).sum()
            for j in range(vcount)
        ])

        magg = adata.obs.groupby(community_key, observed=False)[[y_key]].mean()[y_key]
        _adic = magg.to_numpy()[np.argsort(magg.index.codes)]
        #mean_age = np.array([_adic[i] for i in adata.obs[community_key]])

        cweightsum = c_weights.sum(axis=1)
        if (cweightsum == 0).any():
            logging.warning(f'There are cells n={(cweightsum == 0).sum()} that cannot be assigned to the scaffold (no edges)')
            cweightsum[cweightsum == 0] = 1
        _layout = np.c_[
            (_xlayout / cweightsum),
            -_adic
        ]

        _upd()

        ### construct graph

        # single cell level
        X = _layout[_membership]
        #X[:,0] *= scaffold_scale

        if return_coarse:
            adata.obsm['X_coarse_landscape'] = X.copy()

        ### do the spreading

        if y_mean_init == False:
            ykey = adata.obs[y_key].to_numpy()
            X = np.c_[X[:, 0], -ykey]

        _upd()

        from umap import UMAP

        _upd()

        ids, dists = Graph._umap_compatible(adata.obsp['distances'])
        X_umap = UMAP(
            n_neighbors=ids.shape[1],
            n_epochs=umap_epochs,
            min_dist=umap_min_dist,
            spread=umap_spread,
            init=X,
            precomputed_knn=(ids, dists)
        ).fit_transform(adata.obsm[embedding_key].copy())

        if force_post_y:
            X_umap = np.c_[X_umap[:, 0], -ykey]

        adata.obsm['X_landscape'] = X_umap

        _upd()

        return None
